name: Jack Gillin
analytics: {}
github: true
description: Tech Entrepreneur
author:
  name: Jack Gillin
  email: jgillin@mac.com
collections:
  - index:
      path: /
      number: 15
      paginate: true
      navigable: true
    permalink:
      path: '/:title/'
    feed:
      path: /rss.xml
      format: rss
      number: 10
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/b58c55d7-4dc3-40dd-8f19-4d33066f824c.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/b58c55d7-4dc3-40dd-8f19-4d33066f824c.jpg
    metadata:
      author: []
      datePublished: null
      keywords: []
      '@type': MediaObject
      publisher:
        favicon: null
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
      related: []
      app_links: []
      '@context': 'http://schema.org'
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
navigation:
  - id: ea2309b1-4928-4e1b-b7d3-e623c65889cd
    name: 1st Post
    type: content
layout_spectrum: 0.1745435
color:
  lightness: 0.1595059
  brandColors:
    - '#000000'
    - '#FFFFFF'
    - '#B4B4B4'
    - '#919191'
    - '#414141'
  saturation: 0.8495045
  brandStrength: 0.9957488
  rhythmicContrast: 0.6407089
content_rating:
  adult: false
typography_spectrum: 0.5580022
opengraph: {}
title: Jack Gillin
url: 'http://jackgillin.com/'
